### ISSUE TITLE
com.niclas_van_eyk.laravel_make_integration.run.NoInterpreterSetException

### ISSUE THREAD

**Issue by ksorbo** [NiclasvanEyk/jetbrains-laravel-make-integration#28]
Getting this error without even using the plugin:

com.niclas_van_eyk.laravel_make_integration.run.NoInterpreterSetException
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.inferInterpreter(PHPScriptRun.kt:111)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.<init>(PHPScriptRun.kt:34)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.execute(Artisan.kt:42)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.execute$default(Artisan.kt:32)
	at com.niclas_van_eyk.laravel_make_integration.laravel.artisan.ProjectCommands$inferFromHelp$1.run(ProjectCommands.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by NiclasvanEyk** [comment]
I have a guess why this issue comes up. I suppose you have not php project Interpreter set in the Settings?

I will try to push a fix in the next few days, this should definitely not happen and can be prevented quite easily.
