### ISSUE TITLE
Exception in plugin Laravel Make Integration (2.3.4)

### ISSUE THREAD

**Issue by giannibottoni** [NiclasvanEyk/jetbrains-laravel-make-integration#29]
com.intellij.execution.ExecutionException: PHP home is not specified or invalid.
	at com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.findPhpBinary(PhpCommandSettingsBuilder.java:178)
	at com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.createLocalSettings(PhpCommandSettingsBuilder.java:119)
	at com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.build(PhpCommandSettingsBuilder.java:75)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.buildCommand(PHPScriptRun.kt:68)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.<init>(PHPScriptRun.kt:33)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.execute(Artisan.kt:42)
	at com.niclas_van_eyk.laravel_make_integration.laravel.artisan.ProjectCommands$inferFromHelp$1.run(ProjectCommands.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by NiclasvanEyk** [comment]
Hi, thanks for reporting this issue!
Could you maybe provide a more detailed description of what steps you took to arrive at this error?
I would be especially interested on the configured project interpreter under Settings > Languages & Frameworks > PHP
