### ISSUE TITLE
Can't create controller in app\Http\Controllers

### ISSUE THREAD

**Issue by thatsalltheyare** [NiclasvanEyk/jetbrains-laravel-make-integration#35]
Using laravel 8 I get this message:
```
com.intellij.execution.ExecutionException: PHP home is not specified or invalid.
	at com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.findPhpBinary(PhpCommandSettingsBuilder.java:178)
	at com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.createLocalSettings(PhpCommandSettingsBuilder.java:119)
	at com.jetbrains.php.config.commandLine.PhpCommandSettingsBuilder.build(PhpCommandSettingsBuilder.java:75)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.buildCommand(PHPScriptRun.kt:68)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.<init>(PHPScriptRun.kt:33)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.execute(Artisan.kt:42)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.make(Artisan.kt:25)
	at com.niclas_van_eyk.laravel_make_integration.actions.ArtisanMakeSubCommandActionExecution$execute$cancelled$1.run(ArtisanMakeSubCommandActionExecution.kt:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:298)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:83)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I used the right click menu and then clicked the controller option.

**Comment by NiclasvanEyk** [comment]
It looks like your project interpreter is misconfigured, due to maybe some pacakge manager upgrading php versions, with PHPStorm has not noticed yet.

Could you maybe screenshot your interpreter configuration ([docs](https://www.jetbrains.com/help/phpstorm/configuring-local-interpreter.html))?
As an example, mine looks like this:

<img width="1316" alt="Screen Shot 2021-12-17 at 16 48 25" src="https://user-images.githubusercontent.com/10284694/146571040-7f7b0a36-8ebf-4ce6-b53d-6575d4be56ae.png">

**Comment by thatsalltheyare** [comment]
Ah that was the problem. Thanks!
