### ISSUE TITLE
java.util.NoSuchElementException: Collection contains no element matching the predicate

### ISSUE THREAD

**Issue by lsosorio** [NiclasvanEyk/jetbrains-laravel-make-integration#9]
Hi, i have the next error when i tried to created a model 

java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.inferLocalInterpreter(PHPScriptRun.kt:120)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.inferInterpreter(PHPScriptRun.kt:106)
	at com.niclas_van_eyk.laravel_make_integration.run.PHPScriptRun.<init>(PHPScriptRun.kt:28)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.execute(Artisan.kt:31)
	at com.niclas_van_eyk.laravel_make_integration.laravel.Artisan.make(Artisan.kt:19)
	at com.niclas_van_eyk.laravel_make_integration.actions.ArtisanMakeSubCommandActionExecution$execute$cancelled$1.run(ArtisanMakeSubCommandActionExecution.kt:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:274)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:490)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by NiclasvanEyk** [comment]
Hi, I think you are getting this error, because there is no PHP interpreter configured. When https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/pull/8/commits/ee3a2e175a30bbb1b12e3812cc9419c92a09372d gets published, these errors will be handled in a more user friendly way (by showing a notification containing some guidance).

If you go to Settings > Languages & Frameworks > PHP you can specify the interpreter that the IDE uses to run scripts (e.g. the artisan script)

**Comment by NiclasvanEyk** [comment]
Fixed in [v2.2.0](https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/releases/tag/v2.2.0), which is currently getting reviewed by Jetbrains and will be published later this week.

Feel free to open this again, if any issues arise.
